apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
  namespace: asset-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      serviceAccountName: asset-mgmt-app
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2
          args:
            - "--structured-logs"
            - "--address=0.0.0.0"
            - "--port=3306"
            - "cloud-native-project-494008:asia-east1:asset-mgmt-db"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
