"""sync_hsiu_and_yvonne_models

Revision ID: 0c6ab12b5d94
Revises: 99cadff67b78
Create Date: 2026-04-21 09:54:24.844697+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c6ab12b5d94'
down_revision: str | Sequence[str] | None = '99cadff67b78'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('attachments',
    # sa.Column('id', sa.BigInteger(), nullable=False),
    # sa.Column('attachable_type', sa.Enum('REPAIR_REQUEST', 'REPAIR_INSPECTION', 'REPAIR_RECORD', name='attachment_attachable_type'), nullable=False),
    # sa.Column('attachable_id', sa.BigInteger(), nullable=False),
    # sa.Column('file_url', sa.String(length=1024), nullable=False),
    # sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'OTHER', name='attachment_file_type'), nullable=False),
    # sa.Column('file_name', sa.String(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_attachments_attachable_id'), 'attachments', ['attachable_id'], unique=False)
    # op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_foreign_key(None, 'repair_inspections', 'users', ['checked_by'], ['id'])
    # op.drop_column('repair_inspections', 'photo_url1')
    # op.drop_column('repair_inspections', 'photo_url2')
    # op.drop_column('repair_inspections', 'photo_url3')
    op.alter_column('repair_records', 'vendor',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'repair_requests', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'repair_requests', 'assets', ['asset_id'], ['id'])
    # op.drop_column('repair_requests', 'photo_url1')
    # op.drop_column('repair_requests', 'photo_url2')
    # op.drop_column('repair_requests', 'photo_url3')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.add_column('repair_requests', sa.Column('photo_url3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('repair_requests', sa.Column('photo_url2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('repair_requests', sa.Column('photo_url1', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'repair_requests', type_='foreignkey')
    op.drop_constraint(None, 'repair_requests', type_='foreignkey')
    op.alter_column('repair_records', 'vendor',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
    op.add_column('repair_inspections', sa.Column('photo_url3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('repair_inspections', sa.Column('photo_url2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('repair_inspections', sa.Column('photo_url1', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'repair_inspections', type_='foreignkey')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_attachable_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
