"""make relations of office_locations and vendors

Revision ID: e1258e5d49bf
Revises: 9d0e1f2a3b4c
Create Date: 2026-05-20 07:46:36.374964+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1258e5d49bf'
down_revision: str | Sequence[str] | None = '9d0e1f2a3b4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _has_column(conn, table: str, column: str) -> bool:
    insp = sa.inspect(conn)
    return any(c['name'] == column for c in insp.get_columns(table))


def _has_fk_on(conn, table: str, column: str) -> bool:
    insp = sa.inspect(conn)
    return any(column in fk['constrained_columns'] for fk in insp.get_foreign_keys(table))


def upgrade() -> None:
    conn = op.get_bind()

    op.alter_column('asset_transfers', 'is_offboarding_transfer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('asset_transfers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # assets: vendor_id 欄位可能已存在（部分套用），跳過重複 ADD COLUMN
    if not _has_column(conn, 'assets', 'vendor_id'):
        op.add_column('assets', sa.Column('vendor_id', sa.BigInteger(), nullable=False))
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    if not _has_fk_on(conn, 'assets', 'vendor_id'):
        op.create_foreign_key(None, 'assets', 'vendors', ['vendor_id'], ['id'])
    if _has_column(conn, 'assets', 'vendor'):
        op.drop_column('assets', 'vendor')

    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # repair_records: vendor_id
    if not _has_column(conn, 'repair_records', 'vendor_id'):
        op.add_column('repair_records', sa.Column('vendor_id', sa.BigInteger(), nullable=False))
    if not _has_fk_on(conn, 'repair_records', 'vendor_id'):
        op.create_foreign_key(None, 'repair_records', 'vendors', ['vendor_id'], ['id'])
    if _has_column(conn, 'repair_records', 'vendor'):
        op.drop_column('repair_records', 'vendor')

    op.alter_column('repair_requests', 'loaner_return_borrower_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('repair_requests', 'loaner_return_lender_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)

    # users: location_id
    if not _has_column(conn, 'users', 'location_id'):
        op.add_column('users', sa.Column('location_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    if not _has_fk_on(conn, 'users', 'location_id'):
        op.create_foreign_key(None, 'users', 'office_locations', ['location_id'], ['id'])
    if _has_column(conn, 'users', 'location'):
        op.drop_column('users', 'location')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_column('users', 'location_id')
    op.alter_column('repair_requests', 'loaner_return_lender_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('repair_requests', 'loaner_return_borrower_confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.add_column('repair_records', sa.Column('vendor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'repair_records', type_='foreignkey')
    op.drop_column('repair_records', 'vendor_id')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.add_column('assets', sa.Column('vendor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('assets', 'vendor_id')
    op.alter_column('asset_transfers', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('asset_transfers', 'is_offboarding_transfer',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    # ### end Alembic commands ###
