"""add assets audit_logs departments notification_preferences users

Revision ID: 9779753c668e
Revises: 0001
Create Date: 2026-04-15 13:52:43.943197+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9779753c668e'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.CHAR(length=9), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'ADMIN', name='role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='action'), nullable=False),
    sa.Column('target_type', sa.Enum('ASSET', 'RepairRequest', name='targettype'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'SLACK', 'TEAMS', name='notetype'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('asset_code', sa.CHAR(length=10), nullable=False))
    op.add_column('assets', sa.Column('type', sa.Enum('LAPTOP', 'DESKTOP', 'PHONE', 'TABLET', 'SERVER', 'NETWORK', 'OTHER', name='assettype'), nullable=False))
    op.add_column('assets', sa.Column('model', sa.String(length=255), nullable=False))
    op.add_column('assets', sa.Column('specification', sa.String(length=255), nullable=False))
    op.add_column('assets', sa.Column('vendor', sa.String(length=100), nullable=False))
    op.add_column('assets', sa.Column('purchase_date', sa.Date(), nullable=False))
    op.add_column('assets', sa.Column('purchase_price', sa.Integer(), nullable=False))
    op.add_column('assets', sa.Column('storage_location', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('owner_id', sa.BigInteger(), nullable=True))
    op.add_column('assets', sa.Column('activation_date', sa.Date(), nullable=False))
    op.add_column('assets', sa.Column('warranty_expiry', sa.Date(), nullable=False))
    op.add_column('assets', sa.Column('status', sa.Enum('IN_USE', 'MAINTENANCE', 'BORROWED', 'AVAILABLE', name='assetstatus'), nullable=False))
    op.add_column('assets', sa.Column('version', sa.Integer(), nullable=False))
    op.alter_column('assets', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('uq_assets_path', table_name='assets')
    op.create_unique_constraint(None, 'assets', ['asset_code'])
    op.create_foreign_key(None, 'assets', 'users', ['owner_id'], ['id'])
    op.drop_column('assets', 'size_bytes')
    op.drop_column('assets', 'path')
    op.drop_column('assets', 'content_type')
    op.drop_column('assets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('assets', sa.Column('content_type', mysql.VARCHAR(length=127), nullable=True))
    op.add_column('assets', sa.Column('path', mysql.VARCHAR(length=512), nullable=False))
    op.add_column('assets', sa.Column('size_bytes', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='unique')
    op.create_index('uq_assets_path', 'assets', ['path'], unique=True)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('assets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('assets', 'version')
    op.drop_column('assets', 'status')
    op.drop_column('assets', 'warranty_expiry')
    op.drop_column('assets', 'activation_date')
    op.drop_column('assets', 'owner_id')
    op.drop_column('assets', 'storage_location')
    op.drop_column('assets', 'purchase_price')
    op.drop_column('assets', 'purchase_date')
    op.drop_column('assets', 'vendor')
    op.drop_column('assets', 'specification')
    op.drop_column('assets', 'model')
    op.drop_column('assets', 'type')
    op.drop_column('assets', 'asset_code')
    op.drop_table('notification_preferences')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
