"""add_returned_status_reject_reason_repair_record_attachment_asset_transfers

Revision ID: 4385d7a8eef7
Revises: 6ca2a962c478
Create Date: 2026-05-14 12:11:13.404912+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4385d7a8eef7'
down_revision: str | Sequence[str] | None = '6ca2a962c478'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_transfers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_id', sa.BigInteger(), nullable=False),
    sa.Column('from_owner_id', sa.BigInteger(), nullable=False),
    sa.Column('to_owner_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='asset_transfer_status'), nullable=False),
    sa.Column('from_confirmed', sa.Boolean(), nullable=False),
    sa.Column('to_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('repair_requests', sa.Column('reject_reason', sa.Text(), nullable=True))
    # MySQL enum 變更需手動指定
    op.alter_column(
        'repair_requests', 'status',
        existing_type=mysql.ENUM('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='repair_request_status'),
        type_=mysql.ENUM('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', 'RETURNED', name='repair_request_status'),
        nullable=False,
    )
    op.alter_column(
        'attachments', 'attachable_type',
        existing_type=mysql.ENUM('REPAIR_REQUEST', 'REPAIR_INSPECTION', name='attachment_attachable_type'),
        type_=mysql.ENUM('REPAIR_REQUEST', 'REPAIR_INSPECTION', 'REPAIR_RECORD', name='attachment_attachable_type'),
        nullable=False,
    )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column(
        'attachments', 'attachable_type',
        existing_type=mysql.ENUM('REPAIR_REQUEST', 'REPAIR_INSPECTION', 'REPAIR_RECORD', name='attachment_attachable_type'),
        type_=mysql.ENUM('REPAIR_REQUEST', 'REPAIR_INSPECTION', name='attachment_attachable_type'),
        nullable=False,
    )
    op.alter_column(
        'repair_requests', 'status',
        existing_type=mysql.ENUM('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', 'RETURNED', name='repair_request_status'),
        type_=mysql.ENUM('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='repair_request_status'),
        nullable=False,
    )
    op.drop_column('repair_requests', 'reject_reason')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_table('asset_transfers')
    # ### end Alembic commands ###
