"""add ticket

Revision ID: c5b18111de93
Revises: 0001
Create Date: 2026-04-15 03:12:38.977805+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5b18111de93'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('need_backup', sa.Boolean(), nullable=False),
    sa.Column('backup_spec', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='repair_request_status'), nullable=False),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('pickup_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('photo_url1', sa.String(length=255), nullable=True),
    sa.Column('photo_url2', sa.String(length=255), nullable=True),
    sa.Column('photo_url3', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_requests_id'), 'repair_requests', ['id'], unique=False)
    op.create_table('repair_inspections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.BigInteger(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('photo_url1', sa.String(length=255), nullable=True),
    sa.Column('photo_url2', sa.String(length=255), nullable=True),
    sa.Column('photo_url3', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_repair_inspections_id'), 'repair_inspections', ['id'], unique=False)
    op.create_table('repair_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('repair_date', sa.Date(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_repair_records_id'), 'repair_records', ['id'], unique=False)
    # op.alter_column('assets', 'size_bytes',
    #            existing_type=mysql.BIGINT(display_width=20),
    #            server_default=None,
    #            existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # op.alter_column('assets', 'updated_at',
    #            existing_type=mysql.DATETIME(),
    #            server_default=sa.text('now()'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.alter_column('assets', 'size_bytes',
               existing_type=mysql.BIGINT(display_width=20),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_repair_records_id'), table_name='repair_records')
    op.drop_table('repair_records')
    op.drop_index(op.f('ix_repair_inspections_id'), table_name='repair_inspections')
    op.drop_table('repair_inspections')
    op.drop_index(op.f('ix_repair_requests_id'), table_name='repair_requests')
    op.drop_table('repair_requests')
    # ### end Alembic commands ###
