"""apply indexing

Revision ID: 6ca2a962c478
Revises: be22246ccd33
Create Date: 2026-05-04 05:16:21.014212+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ca2a962c478'
down_revision: str | Sequence[str] | None = 'be22246ccd33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(index.get('name') == index_name for index in indexes)


def _create_index_if_missing(index_name: str, table_name: str, columns: list[str]) -> None:
    if not _index_exists(table_name, index_name):
        op.create_index(index_name, table_name, columns, unique=False)


def _drop_index_if_exists(index_name: str, table_name: str) -> None:
    if _index_exists(table_name, index_name):
        op.drop_index(index_name, table_name=table_name)


def _get_users_department_fk_name() -> str | None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    for fk in inspector.get_foreign_keys('users'):
        if (
            fk.get('referred_table') == 'departments'
            and fk.get('constrained_columns') == ['department_id']
        ):
            return fk.get('name')
    return None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    _create_index_if_missing('ix_assets_status_id', 'assets', ['status', 'id'])
    _drop_index_if_exists('ix_attachments_attachable_id', 'attachments')
    _drop_index_if_exists('ix_attachments_id', 'attachments')
    _create_index_if_missing('ix_attachments_attachable_type_id', 'attachments', ['attachable_type', 'attachable_id'])
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    users_department_fk = _get_users_department_fk_name()
    if users_department_fk:
        op.drop_constraint(users_department_fk, 'users', type_='foreignkey')
    op.alter_column('departments', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    _drop_index_if_exists('ix_repair_inspections_id', 'repair_inspections')
    _drop_index_if_exists('ix_repair_records_id', 'repair_records')
    _drop_index_if_exists('ix_repair_requests_id', 'repair_requests')
    op.alter_column('users', 'department_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    if not _get_users_department_fk_name():
        op.create_foreign_key(
            'fk_users_department_id_departments',
            'users',
            'departments',
            ['department_id'],
            ['id'],
        )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    users_department_fk = _get_users_department_fk_name()
    if users_department_fk:
        op.drop_constraint(users_department_fk, 'users', type_='foreignkey')
    op.alter_column('users', 'department_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.create_index('ix_repair_requests_id', 'repair_requests', ['id'], unique=False)
    op.create_index('ix_repair_records_id', 'repair_records', ['id'], unique=False)
    op.create_index('ix_repair_inspections_id', 'repair_inspections', ['id'], unique=False)
    op.alter_column('departments', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    if not _get_users_department_fk_name():
        op.create_foreign_key(
            'fk_users_department_id_departments',
            'users',
            'departments',
            ['department_id'],
            ['id'],
        )
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    _drop_index_if_exists('ix_attachments_attachable_type_id', 'attachments')
    _create_index_if_missing('ix_attachments_id', 'attachments', ['id'])
    _create_index_if_missing('ix_attachments_attachable_id', 'attachments', ['attachable_id'])
    _drop_index_if_exists('ix_assets_status_id', 'assets')
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
