"""enhance audit log actor name target name json detail

Revision ID: be22246ccd33
Revises: a32c46b09076
Create Date: 2026-04-28 07:03:04.797047+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be22246ccd33'
down_revision: str | Sequence[str] | None = 'a32c46b09076'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('actor_name', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('target_name', sa.String(length=255), nullable=True))
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'detail',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               existing_nullable=True)
    op.execute(
        "ALTER TABLE audit_logs MODIFY COLUMN target_type "
        "ENUM('ASSET','TICKET','INSPECTION','RECORD','ATTACHMENT','USER') NOT NULL"
    )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'detail',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.execute(
        "ALTER TABLE audit_logs MODIFY COLUMN target_type "
        "ENUM('ASSET','RepairRequest') NOT NULL"
    )
    op.drop_column('audit_logs', 'target_name')
    op.drop_column('audit_logs', 'actor_name')
    op.alter_column('assets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
