apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend

images:
  - name: asia-east1-docker.pkg.dev/cloud-native-project-494008/asset-mgmt/backend
    newTag: latest
  - name: asia-east1-docker.pkg.dev/cloud-native-project-494008/asset-mgmt/frontend
    newTag: latest
