apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: asset-mgmt-secrets
  namespace: asset-mgmt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: asset-mgmt-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: asset-mgmt-db-password
    - secretKey: SECRET_KEY
      remoteRef:
        key: asset-mgmt-jwt-secret
    - secretKey: SENDER_EMAIL
      remoteRef:
        key: asset-mgmt-sender-email
    - secretKey: GOOGLE_SMTP_PASSWORD
      remoteRef:
        key: asset-mgmt-smtp-password
