apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: cloud-native-project-494008
      auth:
        workloadIdentity:
          clusterLocation: asia-east1
          clusterName: asset-mgmt-cluster
          clusterProjectID: cloud-native-project-494008
          serviceAccountRef:
            name: asset-mgmt-app
            namespace: asset-mgmt
