apiVersion: v1
kind: ServiceAccount
metadata:
  name: asset-mgmt-app
  namespace: asset-mgmt
  annotations:
    iam.gke.io/gcp-service-account: asset-mgmt-sa@cloud-native-project-494008.iam.gserviceaccount.com
